#!/bin/bash

repo="$(git rev-parse --show-toplevel)"
if [ $? -ne 0 ]
then
   echo "setup must be in repo"
   exit 1
fi

cat >"$repo/.git/hooks/pre-push" <<END
#!/bin/bash
export repo="\$(git rev-parse --show-toplevel)"
export branch="\$(git rev-parse --abbrev-ref HEAD)"
find "\$repo" -name ".pre-push-\$branch" \( -execdir ./{} \; -or -quit \)
END
chmod +x "$repo/.git/hooks/pre-push"
